esphome:
  name: esp8266_ds18b20
  platform: ESP8266
  board: d1_mini_pro
wifi:
  ssid: "Rabenherz"
  password: "12345678"
  ap:
    ssid: "Esp8266 2Xds18B20"
    password: "12345678"
captive_portal:
# Enable logging
logger:
# Enable Home Assistant API
api:
  password: "12345678"
ota:
  password: "12345678"

binary_sensor:
  - platform: status
    name: "esp8266_ds18b20_status"
    
  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
      inverted: false
    name: "esp8266_window_wz_1"
    device_class: window
    
  - platform: gpio
    pin: 
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "esp8266_window_wz_2"
    device_class: window
  
output:
  - platform: gpio
    pin: D4
    inverted: True
    id: led

light:
  - platform: binary
    output: led
    name: "esp8266_ds18b20_led"

dallas:
  - pin: D6
    update_interval: 20s
 
sensor:
  - platform: wifi_signal
    name: "esp8266_ds18b20_signal"
    update_interval: 30s

  - platform: dallas
    address: 0x07331671959DFF28
    name: "esp8266_ds18b20_innen"
    
  - platform: dallas
    address: 0x930C01D60727928
    name: "esp8266_ds18b20_aussen"

