esphome:
  name: espcam1
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "Rabenherz"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espcam1 Fallback Hotspot"
    password: "ZS9XKCISWDD6"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "1204"

ota:
  password: "1204"
  
# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: false
  horizontal_mirror: false
  resolution: 800x600

  # Image settings
  name: ESP32Camera
  # ...
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

binary_sensor:
  - platform: status
    name: "ESP32_ Camera_Status"
    
sensor:
  - platform: wifi_signal
    name: "ESP32_Camera_Signal"
    update_interval: 20s

light:
  - platform: binary
    output: gpio_4
    name: "ESP32_Camera_Licht"

