esphome:
  name: waveshare-v1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret hass_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waveshare-V1-Fallback"
    password: "sadfasdfncvtrzw54645yxcvyxcv"

captive_portal:

#- IOs ------------------------
spi:
  clk_pin: D0
  mosi_pin: D1
  
#- Display --------------------
display:
  - platform: waveshare_epaper
    id: e_paper
    cs_pin: D2
    dc_pin: D3
    busy_pin: D4
    reset_pin: D5
    model: 2.90inv2  # 296 x 128
    rotation: 90
    update_interval: 15s
    full_update_every: 1
    lambda: |-
      it.strftime(4, 0, id(font3), TextAlign::TOP_LEFT, "%H:%M", id(esptime).now());
      it.strftime(10, 62, id(font2), TextAlign::TOP_LEFT, "%d. %b. %Y", id(esptime).now());
      
      it.print(290, 0, id(font1), TextAlign::TOP_RIGHT, "Innen");
      it.print(290, 70, id(font1), TextAlign::TOP_RIGHT, "Aussen");
      it.printf(290, 100, id(font2), TextAlign::TOP_RIGHT, "%.1f °C", id(aussen_temperature).state);
      it.printf(290, 30, id(font2), TextAlign::TOP_RIGHT , "%.1f °C", id(innen_temperature).state);
      
      it.filled_rectangle(190, 0, 4, 296);
      it.filled_rectangle(194, 60, 100, 4);
      it.graph(0, 84, id(graph_aussen_temp));


#------------------------------
#- Display Addons -------------
font:
  - file: 'fonts/bahnschrift.ttf'
    id: font1
    size: 16
  - file: 'fonts/bahnschrift.ttf'
    id: font2
    size: 24
  - file: 'fonts/bahnschrift.ttf'
    id: font3
    size: 72

graph:
  # Show bare-minimum auto-ranged graph
  - id: graph_aussen_temp
    sensor: aussen_temperature
    duration: 1h
    width: 191
    height: 44
    x_grid: 5min
    y_grid: 1.0

#- Binary Sensoren ------------
binary_sensor:
  - platform: status
    name: "waveshare-v1 Status"    


#- Sensoren -------------------
sensor:
  - platform: wifi_signal
    name: "waveshare-v1 Signal"
    update_interval: 30s

  - platform: homeassistant
    id: aussen_temperature
    entity_id: sensor.28_05167180e7ff_temperature
    internal: true

  - platform: homeassistant
    id: innen_temperature
    entity_id: sensor.28_051671ad09ff_temperature
    internal: true

time:
  - platform: homeassistant
    id: esptime

