esphome:
  name: bad-esp32

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password: !secret hass_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Bme280 Fallback Hotspot"
    password: "Eac13dbnIAuA"

captive_portal:
#------------------------------

#- IOs ------------------------
i2c:
  - id: bus_1
    sda: 21
    scl: 22
    scan: true
  
#- Display --------------------
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    id: oled_1
    i2c_id: bus_1
    pages:
      - id: page1
        lambda: |-
          it.strftime(2, 2, id(bahnschrift), TextAlign::TOP_LEFT, "%H:%M", id(esptime).now());
      - id: page2
        lambda: |-
         if (id(aussen_temperature).has_state()) {
           it.printf(127, 2, id(bahnschrift), TextAlign::TOP_RIGHT , "Out: %.1f°C", id(aussen_temperature).state);
          }
      - id: page3
        lambda: |-
         if (id(innen_temperature).has_state()) {
           it.printf(127, 2, id(bahnschrift), TextAlign::TOP_RIGHT , "In: %.1f°C", id(innen_temperature).state);
          }
#- Display Addons -------------
font:
  - file: 'fonts/bahnschrift.ttf'
    id: bahnschrift
    size: 22
    
interval:
  - interval: 3s
    then:
      - display.page.show_next: oled_1
      - component.update: oled_1

#- Binary Sensoren ------------
binary_sensor:
  - platform: status
    name: "bad-esp32 Status"    

#- Sensoren -------------------
sensor:
  - platform: wifi_signal
    name: "bad-esp32 Signal"
    update_interval: 30s
    
  - platform: bh1750
    name: "Bad Licht"
    address: 0x23
    i2c_id: bus_1
    update_interval: 20s

  - platform: bme280
    address: 0x76
    i2c_id: bus_1
    update_interval: 20s
    temperature:
      name: "Bad Temperature"
      oversampling: 16x
    pressure:
      name: "Bad Pressure"
    humidity:
      name: "Bad Humidity"

  # Außen Temperature
  - platform: homeassistant 
    id: aussen_temperature
    entity_id: sensor.28_05167180e7ff_temperature
    internal: true
    
  # Innen Temperature
  - platform: homeassistant
    id: innen_temperature
    entity_id: sensor.28_051671ad09ff_temperature
    internal: true

time:
  - platform: homeassistant
    id: esptime
