esphome:
  name: waveshare-v1-esp32
  platform: ESP32
  board: wemos_d1_mini32

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "b1a0595ff1770e668de7a57db7ca11c4"

wifi:
  ssid: "Rabenherz"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waveshare-V1-Esp32"
    password: "mI9dNc6bNwi9"

captive_portal:
spi:
  clk_pin: 5
  mosi_pin: 23

display:
  - platform: st7735
    model: "INITR_18BLACKTAB"
    reset_pin: 18
    cs_pin: 26
    dc_pin: 19
    id: my_display
    rotation: 90
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
