esphome:
  name: st7735-display-esp32

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_api_password

ota:
  password:  !secret hass_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
#- IOs ------------------------
spi:
  clk_pin: 5
  mosi_pin: 23

#- Display --------------------
display:
  - platform: st7735
    model: "INITR_18BLACKTAB"
    reset_pin: 18
    cs_pin: 26
    dc_pin: 19
    id: st7735_display
    rotation: 90
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
    
    lambda: |-
      it.strftime(0, 0, id(font3), TextAlign::TOP_LEFT, "%H:%M", id(esptime).now());
      it.strftime(0, 75, id(font2), TextAlign::TOP_LEFT, "%d. %b. %Y", id(esptime).now());


#- Display Addons -------------
font:
  - file: 'fonts/bahnschrift.ttf'
    id: font1
    size: 16
  - file: 'fonts/bahnschrift.ttf'
    id: font2
    size: 24
  - file: 'fonts/bahnschrift.ttf'
    id: font3
    size: 72

color:
  - id: ca_red
    red: 100%
    green: 0%
    blue: 0%
    white: 0%
    
  - id: ca_yellow1
    red: 100%
    green: 100%
    blue: 0%
    white: 0%
    
  - id: ca_yellow2
    red: 100%
    green: 60%
    blue: 0%
    white: 0%
    
  - id: ca_orang
    red: 100%
    green: 40%
    blue: 0%
    white: 0%
  
  - id: ca_green
    red: 0%
    green: 100%
    blue: 0%
    white: 0%
    
  - id: ca_blue
    red: 0%
    green: 0%
    blue: 100%
    white: 0%
  
#- Binary Sensoren ------------
binary_sensor:
  - platform: status
    name: "St7735-Display Status"    


#- Sensoren -------------------
sensor:
  - platform: wifi_signal
    name: "St7735-Display Signal"
    update_interval: 30s

  - platform: homeassistant
    id: aussen_temperature
    entity_id: sensor.28_05167180e7ff_temperature
    internal: true

  - platform: homeassistant
    id: innen_temperature
    entity_id: sensor.28_051671ad09ff_temperature
    internal: true

time:
  - platform: homeassistant
    id: esptime
        
